spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://120.25.244.6:3306/audio_search?useSSL=false&characterEncoding=utf8
    username: root
    password: Wmdshpy4725!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .html
server:
  tomcat:
    max-http-post-size: 0
    max-swallow-size: